# Source S3 Configuration
source-key: "your_source_access_key"
source-secret: "your_source_secret_key"
source-region: "us-east-1"
source-bucket: "source-bucket-name"
source-endpoint: "s3.amazonaws.com"  # Optional, defaults to s3.amazonaws.com

# Destination S3 Configuration
dest-key: "your_dest_access_key"
dest-secret: "your_dest_secret_key"
dest-region: "us-west-2"
dest-bucket: "destination-bucket-name"
dest-endpoint: "s3.amazonaws.com"  # Optional, defaults to s3.amazonaws.com

# MongoDB Configuration
database: "your_database_name"
collection: "your_collection_name"
connection: "mongodb://username:password@localhost:27017"
filter: '{"sizeint":{"$gt": 0}}'  # Example filter for objects with size > 0

# Performance Settings
limit: 100  # Number of documents to process per batch
ratelimit: 10  # Rate limit for S3 operations per second

# Optional Settings
cpuprofile: "profile.cpu"  # Optional, for CPU profiling 